apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auto-mlops.fullname" . }}-model-api
  labels:
    app.kubernetes.io/name: {{ include "auto-mlops.name" . }}
    app.kubernetes.io/component: model-api
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  MODEL_PATH: /app/models/model.ts
  CLASSES_PATH: /app/models/classes.txt
  IMAGE_SIZE: "{{ .Values.config.imageSize }}"
  REDIS_URL: redis://{{ include "auto-mlops.fullname" . }}-redis:6379/0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auto-mlops.fullname" . }}-web-ui
  labels:
    app.kubernetes.io/name: {{ include "auto-mlops.name" . }}
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  MODEL_API_URL: http://{{ include "auto-mlops.fullname" . }}-model-api:8000/predict
  MODEL_API_HEALTH_URL: http://{{ include "auto-mlops.fullname" . }}-model-api:8000/health
