"""initial_schema

Revision ID: cf06fa948e58
Revises:
Create Date: 2026-02-02 18:22:49.408265

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf06fa948e58"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("original_query", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("project_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("profile", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_sessions_session_id"), ["session_id"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "experiment_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_session_id", sa.Integer(), nullable=False),
        sa.Column("experiment_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("run_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("current_accuracy", sa.Float(), nullable=True),
        sa.Column("current_loss", sa.Float(), nullable=True),
        sa.Column("target_accuracy", sa.Float(), nullable=False),
        sa.Column("best_accuracy", sa.Float(), nullable=False),
        sa.Column("current_config", sa.JSON(), nullable=True),
        sa.Column("improvement_attempt", sa.Integer(), nullable=False),
        sa.Column("max_improvement_attempts", sa.Integer(), nullable=False),
        sa.Column("improvement_history", sa.JSON(), nullable=True),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("artifacts_created", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiment_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_experiment_states_agent_session_id"), ["agent_session_id"], unique=True
        )

    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_session_id", sa.Integer(), nullable=False),
        sa.Column("step_index", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("step_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("tool", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("from_step", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_steps_agent_session_id"), ["agent_session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_steps_agent_session_id"))

    op.drop_table("steps")
    with op.batch_alter_table("experiment_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiment_states_agent_session_id"))

    op.drop_table("experiment_states")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_sessions_session_id"))

    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
