apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: auto-mlops-canary
spec:
  metrics:
    - name: request-success-rate
      interval: 1m
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local:80
          query: |
            sum(rate(inference_requests_total{status="success"}[1m]))
            /
            sum(rate(inference_requests_total[1m]))
