apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: auto-mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
